### PR TITLE
Add Clang support

### PR DESCRIPTION
**Pull request by kubkon**

### CODE REVIEW

**Comment by kubkon** [comment]
@towca In draft as so far I've only had time to test it on a Mac, and dunno whether the proposed changes to cmake build file are OS specific or not. I'll verify later on today whether it works on my linux box and let you know 👍

**Comment by kubkon** [comment]
> @towca In draft as so far I've only had time to test it on a Mac, and dunno whether the proposed changes to cmake build file are OS specific or not. I'll verify later on today whether it works on my linux box and let you know +1

Hmm, it seems to be OS specific (i.e., no problem with clang with the current configuration). I've added a simple check to discriminate between macosx and the rest. I'll test it at home and if everything works np will PR you.

**Comment by towca** [comment]
I think that which flag to use depends directly on the standard library the compiler uses. Perhaps approach similar to [this](https://stackoverflow.com/a/42593128) could be used for determining the library?

**Comment by kubkon** [comment]
Hmm, that looks awfully convoluted. I think it is not worth adding this hack as it won't really make anything clearer. I'm closing for now :+1:

**Pull request closed without merging**
